[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"
author = "WangXXun"

# The title and description fields are primarily for displaying extension info in UI
title = "Light Studio Extension"
description="A lightwidget light studio python extension. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Light"

# Keywords for the extension
keywords = ["kit", "Light", "UI", "Scene authoring tools"]

icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import hnadi.light_studio".
[[python.module]]
name = "hnadi.light_studio"
